dist: trusty
sudo: required
env:
    - SWIFT_VERSION=4.0.3
language:               node_js
node_js:
    - "node"
    - "lts/*"
    - "7"
    - "8"
before_install:
    - npm install -g npm@latest
    - npm install -g eye.js
install:
    - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)" # Install swift
script:
    - eye # JS
    - cd Marsagalia/c/ && make && ./xorshift # Marsagalia's XORShift algorithm
    - cd ../../ISAAC/c/ && make && ./isaac # ISAAC algorithm
    - cd ../../ # Just going back to the repo
    - swiftc Blum_Blum_Shub/swift/random.swift -o blum # Blum Blum Shub Swift
notifications:
  email:                false
